#    (C) Copyright 2023, 2025 Anthony D. Dutoi
# 
#    This file is part of Qode.
# 
#    Qode is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
# 
#    Qode is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with Qode.  If not, see <http://www.gnu.org/licenses/>.
#
# Usage:  python tutorial.py [<scale>]
# See the message printed at the end for how to set the optional <scale>

import sys
import math
import numpy
import tensorly    # can comment out if using numpy directly below
#import torch
#tensorly.set_backend("pytorch")    # default is numpy
from qode.math.tensornet import np_tensor, tl_tensor, evaluate, raw, increment, scalar_value, ContractionError

print("""
Comments in the code explain the basic usage of the TensorNet subpackage.
If everything is working, this should print out a bunch of random numbers 
that are < ~1e-15, a handled message exception from an intentional mistake,
and a single  instance of a warning about extracting individual elements.
""")

p,q,r,s = 'pqrs'        # lower the number of quotes we need to type

############################################################################
### In tensornet, backend is a tensor-local concept, but this file does not
### make use of multiple backends, so we just pick one below.  The factory
### objects np_tensor and tl_tensor imported above act to both wrap "raw"
### tensors (of the type provided by the backend we will be using) and 
### provide other conveniences (like the instantiation of an appropriate
### zeros tensor without instantiating and wrapping in separate steps).
### We set prim_tensor here to the factory that we want to use for now.
### The identifiers zeros and einsum are from the raw backend, and are used
### here for purposes of comparison/testing.

# use numpy directly as backend
#zeros, einsum, prim_tensor =    numpy.zeros,    numpy.einsum, np_tensor

# use tensorly backend (numpy or pytorch, per choices above)
zeros, einsum, prim_tensor = tensorly.zeros, tensorly.einsum, tl_tensor

############################################################################
### Package up some repetitive tasks (making tensors, checking accuracy)

def check(xpt, ref):
    #     numpy
    #return numpy.linalg.norm(xpt - ref) / numpy.linalg.norm(ref)
    #     tensorly (BTW, what tensorly calls \ell^2 is Frobenius)
    return tensorly.norm(xpt - ref) / tensorly.norm(ref)

def random_tensor(*shape):
    #     numpy
    #return numpy.random.random(shape)
    #     tensorly numpy (default)
    return tensorly.tensor(numpy.random.random(shape))
    #     tensorly pytorch
    #return tensorly.tensor(torch.rand(*shape))

############################################################################
### Now, on with the usage tutorial ....



    ### The Basics

# Some original "raw" tensors
A_ = random_tensor(10, 10)
B_ = random_tensor(10,  8)
C_ = random_tensor( 8, 10)
D_ = random_tensor( 8,  8)
U_ = random_tensor(8)
V_ = random_tensor(10)

# Prepare "primitive" tensors for tensornet using wrapping function for raw
# arrays.  The original data is never modified by tensornet machinery.
A = prim_tensor.init(A_)
B = prim_tensor.init(B_)
C = prim_tensor.init(C_)
D = prim_tensor.init(D_)
U = prim_tensor.init(U_)
V = prim_tensor.init(V_)

# For our first set of tests, we will duplicate the result of the following
# "raw" contraction using tensornet syntax.
test = 2 * einsum("pr,rt,sq,ts->pq", A_, B_, C_, D_)

# - The central operation for which tensornet was designed is the building
#   of contraction networks.  Below, the basic synax is illustracted.  It 
#   does no computation at this point; it only logs the inputs necessary
#   to define the network.
# - Each factor connected by @ is generated by a call "()" on the input
#   tensor (primitives here, but can be themselves networks), whose own
#   arguments are either (1) a label non-integer label that specifies that
#   a certain index will be summed, and whose recurrance (if any) specifies
#   indices to be contracted with each other, or (2) an integer whose order
#   specifies the permutation of free indices in the contracted product.
# - Repeated integers specify indices to be set equal to each other (as if
#   contracted with a Kronecker).  Such a thing is called a reduction here.
# - A contraction label (often a letter) can be any hashable object that
#   is not an integer.
# - An exception will be raised if a logical error occurs with the shapes,
#   like contracting indices of incompatible lengths.
# - There is no limit on the number of tensor factors and (to within machine
#   precision) the result will not depend in any way on how they are ordered
#   (not even efficiency).
# - Scalar multiplication is also possible in the same string, but the *
#   operator should be used for scalars.
# Here is now the tensornet syntax and the check of its accuracy:
ABCD1 = 2 * A(0,p) @ B(p,q) @ C(r,1) @ D(q,r)
print("relative error in check  1:", check(raw(ABCD1), test))

# This can also be done in stages as follows
AB2    = A(0,p) @ B(p,1)
CD2    = C(p,1) @ D(0,p)
ABCD2  = AB2(0,p) @ CD2(p,1)
ABCD2 *= 2
print("relative error in check  2:", check(raw(ABCD2), test))

# The point of the next set of definitions is that they are functionally 
# equivalent to the ones above, except in one subtle detail.
AB3    =   (A(0,p) @ B(p,1))()
CD3    =   (C(p,1) @ D(0,p))()
ABCD3  = (AB3(0,p) @ CD3(p,1))()
ABCD3 *= 2
print("relative error in check  3:", check(raw(ABCD3), test))
# The existence of the syntax using the intermediate "()" is mostly just a
# reassurance for the paranoid, but it is important to state why it exists.
# We needed 4 distint indices in test 1 because the expression is still
# "open" after contracting A with B, and using p again in this expression
# (as we do in tests 2 and 3) would be interpreted as the same index (a
# 4-index contraction). Consider that one would then also get an erroneous
# result from
AB4 = 2 * A(0,p) @ B(p,1)
try:
    ABCD4 = AB4 @ C(p,1) @ D(0,p)
except ContractionError as err:
    print(str(err) + "\n") 
# because, according to python syntax, it is equivalent to using p four
# times in the expression just discussed and setting other indices equal
# to each other.  In fact because these dimensions are not even of the
# same length, we do not just get a wrong answer, we get an exception, 
# which is ignored here (but the message is printed as an example). However,
# the following gives the correct result for the second line
ABCD4 = AB4(0,p) @ (C(p,1) @ D(0,p))(p,1)
print("relative error in check  4:", check(raw(ABCD4), test))
# The reason is that we have a concept of "open" and "closed" expressions
# (more technically just expressions (open) and expressions that have been
# resolved to a tensor network (closed)).  The repeated usage of @ and * 
# (for scalars) builds open expressions, but applying any other operation 
# to an open expression closes it before anything else happens.  Once an
# expression has been resolved to a network, it has no memory of the letters
# that were once used to describe its connectivity, and it cannot even enter
# into another expression until a "()" has been performed on it.  Similarly
# acting a "()" on an expression closes it automatically before the action
# of the call is applied.  Though typical uses would not be likely to cause
# one to accidentally extend an open expression, one can close it manually
# without needing to specify indices by using an empty call (which is 
# equivalent to just using call with the arguments (0,1,2,...,<n>-1), where
# <n> is the dimensionality of the result of the expression.

# In the tests above, we have repeatedly used the raw() function.  When
# acting on a tensornet tensor, this triggers evaluation and it returns the
# result as a "raw" backend tensor to the user.  There is a similar
# evaluate() function with returns the result as a tensornet "primitive"
# tensor that can be used in subsequent tensornet expressions.  More on that
# below.

# Below illustrates that +, - and * all work on tensors networks, and the
# call notation "()" can also be used just to permute indices.  The result
# of a scalar multiplication (which is fast) is another tensor network whose
# internal scalar factor is modified.  Similarly, the result of the
# subtraction is an abstracted structure that keeps track of the operation
# but performs no computation until evaluate() or raw() is used.
ABCD_p = 3*ABCD1 - 3*ABCD1(1,0)
test = 3*test - 6*einsum("pr,rt,sq,ts->qp", A_, B_, C_, D_)
print("relative error in check  5:", check(raw(ABCD_p), test))

# This illustrates that there are not many restrictions on the order of the
# arguments or the placement of the indices.  The redundant "1" means that
# the 1 index of the contracted product is resolved by setting these two
# equal to each other.  Also single as well as multiple (not just double)
# occurances of contraction labels are allowed.  Note that the same index
# can occur multiply on any given tensor, and that outer products (A shares
# no indices with others) are allowed.  Finally, if a scalar will be buried
# in the middle of a contraction string, it is best to use @ on both sides
# or else you have to remember to use * only for the first one because of
# the order in which python operators bind.
ABCD3 = A(q,0) @ B(1,p) @ 3 @ C(p,1) @ D(p,p)
test = 3 * einsum("qr,sp,ps,pp->rs", A_, B_, C_, D_)
print("relative error in check  6:", check(raw(ABCD3), test))

# The real utility of tensornet is for something like this.  E represents
# 4-index tensor, but its contractions with vectors can be done faster if
# done internally as contractions with the factors.  The scalar_value()
# function extracts the scalar-typed value from a 0-index tensor (like
# ndarray.item() in numpy).
E = A(0,1) @ D(2,3)
VVEUU = scalar_value(E(p,q,r,s) @ V(p) @ V(q) @ U(r) @ U(s))
test = einsum("pq,rs,p,q,r,s->", A_, D_, V_, V_, U_, U_).item()
print("relative error in check  7:", (VVEUU - test) / test)

# You can take elements of a primitive tensor, ...
print("relative error in check  8:", (A[0,0] - A_[0,0]) / A_[0,0])
# ... or of a tensor network.  For a network, this will reevaluate
# everything for every element requested, so it warns the user the first
# time about this being inefficient (maybe use evaluate() on a block and
# then take elements instead?).  To be clear, tensornet is smart enough not
# evaluate the whole tensor to obtain a single element; it first restricts
# the relevant indices in the primitives before contraction is done.  So, in
# this particular case, it actually is not inefficent.
print("relative error in check  9:",
    (E[0,0,0,0] - A_[0,0]*D_[0,0]) / (A_[0,0]*D_[0,0]))
# Note that it does not warn you a second time.
print("relative error in check 10:",
    (E[1,1,1,1] - A_[1,1]*D_[1,1]) / (A_[1,1]*D_[1,1]))

# Slicing also works, ...
print("relative error in check 11:", check(raw(A[0, 1:5]), A_[0, 1:5]))
# ... within contractions ...
AC = A[:,:8](0,p) @ C(p,1)
test = einsum("pq,qr->pr", A_[:,:8], C_)
print("relative error in check 12:", check(raw(AC), test))
# ... and on tensor networks (where again it first acts to slice the
# primitives in the network before evaluation is done.
test = einsum("p,q->pq", A_[:,0], D_[:,1])
print("relative error in check 13:", check(raw(E[:,0,:,1]), test))



    ### Some Finer Points

# One thing that is good to be aware of is that, if one contracts a sum
# (such as F below), the contractions of the terms are always done first and
# then added (most likely desired and far simpler dispatching algorithm) ...
F = A + 5*B(0,p)@C(p,1)
test = einsum("p,pq,q->", V_, A_, V_) + \
    5 * einsum("p,pq,qr,r->", V_, B_, C_, V_)
print("relative error in check 14:", check(raw(V(p) @ F(p,q) @ V(q)), test))

# ... but the user has control over this by forcing evaluation of the
# intermediate first, if desired.  The evaluate() function performs all
# internal contractions and index reductions and returns a primitive (not a 
# raw) tensor.
print("relative error in check 15:",
    check(raw(V(p) @ evaluate(F)(p,q) @ V(q)), test))

# Should one need to loop over terms to build a sum, an empty accumulator
# can be started as so:
F = prim_tensor.zeros()
for term in [A, 5*B(0,p)@C(p,1)]:    # pretend generated by some algorithm
    F += term
print("relative error in check 16:", check(raw(V(p) @ F(p,q) @ V(q)), test))
# In this example F takes its shape from the first term and the checks that
# the shapes of subsequent terms match.  This means that attempting to
# evaluate F before the summation started would give an exception because it
# has no valid shape, but a shape argument can be given and an explicit
# tensors of zeros would be generated by the backend on demand.

# Here is another way to do this, if you know you want a concrete evaluation
# immediately.  This does not yet save memory with an in-place build, but
# the point is to leave the door open for that to be implemented later
# (presently just a thin wrapper around +=raw(...)).
F_ = zeros(A.shape)
for term in [A, 5*B(0,p)@C(p,1)]:
    increment(F_, term)
print("relative error in check 17:",
    check(einsum("pq,p,q->", F_, V_, V_), test)), 

# Oops, looks like I explained this material twice.  I should pick on
# and probably put it in this location because it is too much at the 
# beginning.
# And now a comment on a subtlty of the @ operator.  By necessity (since
# there is no trigger to tell it to stop), it generates "incomplete"
# contractions.  Consider "ABCD" from above.  Done in the way below, the
# contraction labels q and r must be shared across two lines.  This is a
# potential danger since one might not realize a letter has been shared if
# lines like these are farther apart.  Whereas there might actually be a
# niche use case for this behavior it is mostly just a dark corner.
ABC4  = A(0,p) @ B(p,q) @ C(r,1)
ABCD4 = 2 * ABC4 @ D(q,r)
test = 2 * einsum("pr,rt,sq,ts->pq", A_, B_, C_, D_)
print("relative error in check 18:", check(raw(ABCD4), test))
# However, under normal circumstances, one would not write code in this way,
# so the danger is limited.  If one really means that, in ABC4, q and r
# should be summed over as individual indices, leaveing only two free
# indices in the product, then future contractions should be written more
# like the following (note the call with indices attached to ABC4), where we
# have to choose something other than D just for dimension matching.
ABCB1 = 2 * ABC4(p,0) @ B(p,1)
test = 2 * einsum("pq,qr,st,pu->tu", A_, B_, C_, B_)
print("relative error in check 19:", check(raw(ABCB1), test))
# And as a one-liner, we could have
ABCB2 = 2 * (A(0,p) @ B(p,q) @ C(r,1))(p,0) @ B(p,1)
print("relative error in check 20:", check(raw(ABCB2), test))
# And, just for clarity, this is of course the same (in every way) as
ABCB3 = 2 * A(s,p) @ B(p,q) @ C(r,0) @ B(s,1)
print("relative error in check 21:", check(raw(ABCB3), test))



    ### About Efficiency

# Here is a quick test that shows this code can be smarter than einsum in
# dispataching contractions.
# Setup ...
factor = 1
if len(sys.argv)==2:
    factor = float(sys.argv[1])
dim = math.floor(factor * 10)
M_ = random_tensor(dim, dim, dim, dim)
M  = prim_tensor.init(M_)
T_ = random_tensor(dim, dim)
T  = prim_tensor.init(T_)
# ... and test:
TTMTT = raw(M(p,q,r,s) @ T(p,0) @ T(q,1) @ T(r,2) @ T(s,3))
print("Tensornet done with 4-index transformation.  Waiting on einsum ... ")
# See note about opt_einsum in to-do (default in pytorch and accessible with
# numpy, also via tensorly)
test = einsum("pqrs,pw,qx,ry,sz->wxyz", M_, T_, T_, T_, T_)
print("... einsum done.")
print("relative error in check 22:", check(TTMTT, test))
print("If the timing difference was not dramatic enough, "
    "run the script with a float argument >~1")
print("to scale the dimensions.  But do not go nuts.  "
    "The einsum call scales with the 8th power.")
